### ISSUE TITLE
License authentication

### ISSUE THREAD

**Issue by Horion0415** [LFUSST/MMI-VG#2]
Please confirm whether the models used in this project are original. If the project is based on another project, it needs to be forked. If it only references other models, a license needs to be included to avoid copyright issues.

**Comment by LFUSST** [comment]
Hello ，thank you for your question! Our project was built on top of SeqTR (https://github.com/seanzhuh/SeqTR), and we will build forks in the future.

**Comment by Horion0415** [comment]
Okay, thank you for your contributions to the open-source community.
